FROM debian:jessie

MAINTAINER Björn Kjeholt <dev@kjeholt.se>

ARG DOCKER_IMAGE_NAME
ARG DOCKER_IMAGE_TAG

ENV DOCKER_IMAGE_NAME ${DOCKER_IMAGE_NAME:-UnknownName}
ENV DOCKER_IMAGE_TAG ${DOCKER_IMAGE_TAG:-UnknownRevision}

#
# Install required packages.
#

RUN apt-get -y update && \
    apt-get -y install mysql-client \
                       vim && \
    mkdir -p /sql

#
# Install start script.
#

COPY Scripts /usr/local/bin/
# COPY DatabaseSetup /backup/setups
COPY sql /sql

RUN chmod +rx /usr/local/bin/*.sh 

#
# Set container settings.
#

WORKDIR /backup

#
# Start process.
#

CMD ["/usr/local/bin/setup.sh"]

